### PR TITLE
user check

### PR DESCRIPTION
**Pull request by adrian-renci**
addresses 461 (partially)

### CODE REVIEW

**Review by rajshruti18 — APPROVED** [review]

**Review by rajshruti18 — APPROVED** [review]

**Comment by hyi** [comment]
@rajshruti18 @krobasky @mbwatson @dcarsey I am not sure about this PR by looking at the code changes. It appears to have something to do with global write permissions most likely for HEAL users, but I am not sure what it is aimed for and what issues it addresses. Also, it is in branch2.3 which I assume has never been deployed. Let's review it together and decide what to do with it, but let me know in the meantime you know more details about this PR.

**Comment by rajshruti18** [comment]
> @rajshruti18 @krobasky @mbwatson @dcarsey I am not sure about this PR by looking at the code changes. It appears to have something to do with global write permissions most likely for HEAL users, but I am not sure what it is aimed for and what issues it addresses. Also, it is in branch2.3 which I assume has never been deployed. Let's review it together and decide what to do with it, but let me know in the meantime you know more details about this PR.

Branch 'release2.3' was merged with the master branch while back. 
Screen Shot 2022-01-24 at 1 46 10 PM

**Comment by hyi** [comment]
@rajshruti18 I double checked the master branch and can confirm the code changes in this PR are not included in the master. So perhaps this release2.3 branch to be merged is different from the release you deployed since the release you deployed should already been merged into master?

**Comment by rajshruti18** [comment]
> @rajshruti18 I double checked the master branch and can confirm the code changes in this PR are not included in the master. So perhaps this release2.3 branch to be merged is different from the release you deployed since the release you deployed should already been merged into master?

Please check this https://github.com/RENCI/ctmd-dashboard/commit/e46db2bb3ec8e069e30eb70ee66427b4a5caff09. Adrian named that branch as release 2.3 because he wasn't aware of the naming convention so please don't confuse it's name with the release, it is just a bugfix branch.

**Comment by rajshruti18** [comment]
Check this out: https://github.com/RENCI/ctmd-dashboard/pull/236

**Comment by hyi** [comment]
@rajshruti18 The links you posted are for ctmd-dashboard repo, but this PR is for tic-map-pipeline-script repo. Yeah, agreed this looks like a bugfix branch.

**Comment by rajshruti18** [comment]
> @rajshruti18 The links you posted are for ctmd-dashboard repo, but this PR is for tic-map-pipeline-script repo. Yeah, agreed this looks like a bugfix branch.

I know the link

> @rajshruti18 The links you posted are for ctmd-dashboard repo, but this PR is for tic-map-pipeline-script repo. Yeah, agreed this looks like a bugfix branch.

Yes, I agree with you the release2.3 branch for this repo has not been merged that is why I am seeking your approval for this PR. It will be merged once you approve it.

**Pull request closed without merging**
